import html
import json
from datetime import datetime, timezone

_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;background:#0b0e14;color:#e6e6e6}
header,section,footer{padding:16px 24px;border-bottom:1px solid #1c2130}
h1{margin:0 0 8px;color:#7ee787}
h2{color:#79c0ff;border-left:3px solid #79c0ff;padding-left:8px}
.summary{color:#d2a8ff}
.muted{color:#8b949e;font-size:12px}
table{border-collapse:collapse;width:100%;margin-top:8px;font-size:13px}
th,td{border:1px solid #263041;padding:6px 8px;text-align:left;vertical-align:top}
th{background:#161b22;color:#c9d1d9}
tr:nth-child(even) td{background:#0f141c}
code{color:#7ee787}
"""


def build_report(target, results, meta):
    return {
        "tool": "reconkit",
        "version": meta.get("version", ""),
        "target": target,
        "scope": meta.get("scope", []),
        "started_utc": meta.get("started", ""),
        "finished_utc": datetime.now(timezone.utc).isoformat(),
        "module_count": len(results),
        "modules": results,
    }


def write_json(path, report):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, default=str)


def _table(findings):
    if not findings:
        return "<p class='muted'>No findings.</p>"
    keys = []
    for row in findings:
        for k in row.keys():
            if k not in keys:
                keys.append(k)
    head = "".join("<th>" + html.escape(str(k)) + "</th>" for k in keys)
    rows = []
    for row in findings:
        cells = "".join(
            "<td>" + html.escape(str(row.get(k, ""))) + "</td>" for k in keys
        )
        rows.append("<tr>" + cells + "</tr>")
    return (
        "<table><thead><tr>"
        + head
        + "</tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>"
    )


def write_html(path, report):
    p = []
    p.append("<!doctype html><html><head><meta charset='utf-8'>")
    p.append(
        "<title>reconkit report - "
        + html.escape(str(report.get("target")))
        + "</title>"
    )
    p.append("<style>" + _CSS + "</style></head><body>")
    p.append("<header><h1>reconkit report</h1>")
    p.append(
        "<p><b>Target:</b> <code>"
        + html.escape(str(report.get("target")))
        + "</code></p>"
    )
    p.append(
        "<p><b>Scope:</b> " + html.escape(", ".join(report.get("scope", []))) + "</p>"
    )
    p.append(
        "<p class='muted'>"
        + html.escape(str(report.get("started_utc")))
        + " &rarr; "
        + html.escape(str(report.get("finished_utc")))
        + "</p></header>"
    )
    for mod in report.get("modules", []):
        p.append("<section><h2>" + html.escape(str(mod.get("module"))) + "</h2>")
        p.append("<p class='summary'>" + html.escape(str(mod.get("summary"))) + "</p>")
        p.append(_table(mod.get("findings", [])))
        p.append("</section>")
    p.append(
        "<footer class='muted'>Generated by reconkit &middot; authorized testing only.</footer>"
    )
    p.append("</body></html>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(p))


def write_markdown(path, report):
    lines = []
    lines.append("# reconkit engagement notes")
    lines.append("")
    lines.append("- **Target:** " + str(report.get("target")))
    lines.append("- **Scope:** " + ", ".join(report.get("scope", [])))
    lines.append("- **Started (UTC):** " + str(report.get("started_utc")))
    lines.append("- **Finished (UTC):** " + str(report.get("finished_utc")))
    lines.append("- **Modules run:** " + str(report.get("module_count")))
    lines.append("")
    lines.append("## Findings by module")
    for mod in report.get("modules", []):
        lines.append("")
        lines.append("### " + str(mod.get("module")) + " - " + str(mod.get("summary")))
        findings = mod.get("findings", [])
        if not findings:
            lines.append("_No findings._")
            continue
        keys = []
        for row in findings:
            for k in row.keys():
                if k not in keys:
                    keys.append(k)
        lines.append("| " + " | ".join(keys) + " |")
        lines.append("| " + " | ".join(["---"] * len(keys)) + " |")
        for row in findings:
            cells = [
                str(row.get(k, "")).replace("|", "\\|").replace("\n", " ") for k in keys
            ]
            lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("## Suggested next steps")
    lines.append("- Manually validate each finding before reporting.")
    lines.append(
        "- Prioritize secrets, exposed .git/.env, default creds, and open redirects."
    )
    lines.append("- Only continue testing systems that are in scope and authorized.")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
