"""Offline, socket-free validation harness for reconkit.

Simulates the Acme lab app with a FakeHttp client so every HTTP/OSINT module's
logic is exercised without any network. Also generates the real report
artifacts (report.json, report.html, notes.md). Network (socket) modules
(ports, udp, dns, subdomains, subbrute, tls) are validated by compile+import
and run on a live network.

Run:  python3 unit_tests.py
"""

import base64
import os
import sys
from datetime import datetime, timezone
from urllib.parse import parse_qs, urlparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import lab.labapp as labapp
from reconkit.core import report as reportmod
from reconkit.core.http import Resp
from reconkit.modules import (
    cookies,
    cors,
    crtsh,
    defaultcreds,
    dirs,
    fingerprint,
    headers,
    injection,
    misconfig,
    openredirect,
    params,
    robots,
    secrets,
    spider,
    takeover,
    waf,
    wayback,
    whois,
    wordlist,
)

INDEX, APPJS, ROBOTS, SITEMAP = (
    labapp.INDEX,
    labapp.APPJS,
    labapp.ROBOTS,
    labapp.SITEMAP,
)
ADMIN_AUTH = "Basic " + base64.b64encode(b"admin:admin").decode()


class FakeHttp:
    def get(self, url, allow_redirects=True, max_bytes=300000, headers=None, data=None):
        return self._route(url, headers or {})

    def head(self, url, **kw):
        return self._route(url, kw.get("headers") or {})

    def post(self, url, data=None, **kw):
        return self._route(url, kw.get("headers") or {})

    def request(
        self,
        url,
        method="GET",
        allow_redirects=True,
        max_bytes=300000,
        headers=None,
        data=None,
    ):
        return self._route(url, headers or {})

    def external(self, url, headers=None, max_bytes=1000000):
        return None

    def _route(self, url, headers):
        h = {k.lower(): v for k, v in (headers or {}).items()}
        u = urlparse(url)
        host = u.netloc.split(":")[0].lower()
        path = u.path or "/"
        low = (u.query or "").lower()
        if host.startswith("dangling"):
            body = "<html>NoSuchBucket: The specified bucket does not exist</html>"
            return Resp(
                url,
                404,
                {"content-type": "text/html", "server": "AmazonS3"},
                body.encode(),
                [],
            )
        if path == "/robots.txt":
            return Resp(url, 200, {"content-type": "text/plain"}, ROBOTS.encode(), [])
        if path == "/sitemap.xml":
            return Resp(
                url, 200, {"content-type": "application/xml"}, SITEMAP.encode(), []
            )
        if path == "/static/app.js":
            return Resp(
                url, 200, {"content-type": "application/javascript"}, APPJS.encode(), []
            )
        if path == "/admin":
            if h.get("authorization") == ADMIN_AUTH:
                return Resp(
                    url,
                    200,
                    {"content-type": "text/html"},
                    b"<html>admin dashboard</html>",
                    [],
                )
            return Resp(
                url, 401, {"www-authenticate": 'Basic realm="admin"'}, b"401", []
            )
        if path in ("/go", "/redirect"):
            qs = parse_qs(u.query)
            dest = (
                qs.get("url")
                or qs.get("next")
                or qs.get("redirect")
                or qs.get("u")
                or qs.get("dest")
                or [""]
            )[0]
            if dest:
                return Resp(url, 302, {"location": dest}, b"", [])
            return Resp(
                url, 200, {"content-type": "text/html"}, b"redirect service", []
            )
        if path == "/search":
            qs = parse_qs(u.query, keep_blank_values=True)
            q = (qs.get("q") or [""])[0]
            if "'" in q:
                body = (
                    "<html>Database error: You have an error in your SQL syntax near '"
                    + q
                    + "'</html>"
                )
                return Resp(url, 500, {"content-type": "text/html"}, body.encode(), [])
            body = "<html><body>Results for: " + q + "</body></html>"
            return Resp(url, 200, {"content-type": "text/html"}, body.encode(), [])
        if path == "/":
            if ("<script" in low) or ("or '1'='1" in low) or ("etc/passwd" in low):
                return Resp(
                    url,
                    403,
                    {"content-type": "text/html", "server": "Apache"},
                    b"<html>Access Denied. This error was generated by Mod_Security.</html>",
                    [],
                )
            rh = {
                "content-type": "text/html",
                "server": "Apache/2.4.29 (Ubuntu)",
                "x-powered-by": "PHP/7.4.3",
            }
            if h.get("origin"):
                rh["access-control-allow-origin"] = h["origin"]
                rh["access-control-allow-credentials"] = "true"
            cookies_out = [
                "sessionid=abc123def456; Path=/",
                "secure_ok=1; Path=/; Secure; HttpOnly; SameSite=Strict",
            ]
            return Resp(url, 200, rh, INDEX.encode(), cookies_out)
        return Resp(
            url, 404, {"content-type": "text/html"}, b"<html>404 Not Found</html>", []
        )


class _Rate:
    def wait(self):
        pass


class _Scope:
    def allows(self, host):
        return True


class FakeCtx:
    def __init__(self):
        self.http = FakeHttp()
        self.workers = 8
        self.timeout = 3.0
        self.rate = _Rate()
        self.scope = _Scope()
        self.options = {
            "ports": "",
            "udp_ports": "",
            "wordlist": "",
            "sub_wordlist": "",
            "param_wordlist": "",
            "max_pages": 10,
            "tls_port": 0,
            "out_wordlist": "",
            "top_words": 40,
            "cookie": "",
            "auth_header": "",
            "user_agent": "",
            "creds": "",
        }


def main():
    ctx = FakeCtx()
    target = "http://lab.test"
    results = []
    fails = []

    def run(mod, tgt=target):
        res = mod.run(tgt, ctx)
        results.append(res)
        return res

    def check(cond, msg):
        if not cond:
            fails.append(msg)

    r = run(robots)
    check(len(r["findings"]) == 6, "robots findings=%d want 6" % len(r["findings"]))

    r = run(params)
    check(
        r["data"].get("forms") == 2, "params forms=%s want 2" % r["data"].get("forms")
    )
    check(
        r["data"].get("query_params") == 4,
        "params query_params=%s want 4" % r["data"].get("query_params"),
    )

    r = run(cookies)
    check(len(r["findings"]) == 2, "cookies findings=%d want 2" % len(r["findings"]))
    check(r["data"].get("weak") == 1, "cookies weak=%s want 1" % r["data"].get("weak"))

    r = run(waf)
    check(
        "mod_security" in r["data"].get("vendors", []),
        "waf vendors=%s" % r["data"].get("vendors"),
    )
    check(
        r["data"].get("blocked_payloads", 0) >= 1,
        "waf blocked=%s" % r["data"].get("blocked_payloads"),
    )

    r = run(cors)
    issues = " ".join(f.get("issue", "") for f in r["findings"]).lower()
    check(len(r["findings"]) >= 2, "cors findings=%d want>=2" % len(r["findings"]))
    check("reflect" in issues, "cors issues missing reflect: %s" % issues)
    check("null" in issues, "cors issues missing null: %s" % issues)

    r = run(openredirect)
    check(
        len(r["findings"]) == 2, "openredirect findings=%d want 2" % len(r["findings"])
    )

    r = run(secrets)
    stypes = " ".join(f.get("type", "") for f in r["findings"]).lower()
    check(len(r["findings"]) >= 3, "secrets findings=%d want>=3" % len(r["findings"]))
    check("aws" in stypes, "secrets types missing aws: %s" % stypes)
    check("google" in stypes, "secrets types missing google: %s" % stypes)

    r = run(injection)
    itypes = " ".join(f.get("type", "") for f in r["findings"]).lower()
    check("reflect" in itypes, "injection missing reflect: %s" % itypes)
    check("sql" in itypes, "injection missing sql: %s" % itypes)

    r = run(takeover, "http://dangling.lab.test")
    check(len(r["findings"]) >= 1, "takeover findings=%d want>=1" % len(r["findings"]))

    r = run(defaultcreds)
    check(
        r["data"].get("realms", 0) >= 1,
        "defaultcreds realms=%s" % r["data"].get("realms"),
    )
    check(
        len(r["findings"]) >= 1, "defaultcreds findings=%d want>=1" % len(r["findings"])
    )

    r = run(headers)
    check(
        r["data"].get("missing", 0) >= 5,
        "headers missing=%s want>=5" % r["data"].get("missing"),
    )

    r = run(fingerprint)
    check(
        len(r["findings"]) >= 2, "fingerprint findings=%d want>=2" % len(r["findings"])
    )

    r = run(spider)
    check(
        r["data"].get("pages", 0) >= 1,
        "spider pages=%s want>=1" % r["data"].get("pages"),
    )
    check(
        r["data"].get("emails", 0) >= 1,
        "spider emails=%s want>=1" % r["data"].get("emails"),
    )

    r = run(wordlist)
    check(len(r["findings"]) >= 1, "wordlist findings=%d want>=1" % len(r["findings"]))

    run(dirs)
    run(misconfig)

    for mod in (whois, crtsh, wayback):
        r = run(mod)
        check(not r["findings"], mod.NAME + " should degrade offline")

    meta = {
        "version": "2.2.0",
        "scope": ["lab.test"],
        "started": datetime.now(timezone.utc).isoformat(),
    }
    rep = reportmod.build_report(target, results, meta)
    reportmod.write_json("./report.json", rep)
    reportmod.write_html("./report.html", rep)
    reportmod.write_markdown("./notes.md", rep)

    print("MODULES TESTED:", len(results))
    print("VERSION:", rep.get("version"))
    for res in results:
        print("  %-13s %3d  %s" % (res["module"], len(res["findings"]), res["summary"]))
    print("FAILS:", fails)
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
