from ..core.utils import base_url, good, make_result, warn

NAME = "waf"
DESCRIPTION = "WAF / security-filter detection"

SIGNATURES = {
    "cloudflare": ["cloudflare", "cf-ray", "__cfduid", "attention required"],
    "akamai": ["akamai", "akamaighost"],
    "incapsula/imperva": ["incap_ses", "visid_incap", "incapsula"],
    "sucuri": ["sucuri", "x-sucuri-id"],
    "aws waf": ["awselb", "aws-waf", "x-amzn-requestid"],
    "mod_security": ["mod_security", "modsecurity", "generated by mod_security"],
    "f5 big-ip asm": ["big-ip", "bigipserver", "the requested url was rejected"],
    "barracuda": ["barra_counter_session", "barracuda"],
    "fortinet": ["fortiweb", "fortigate"],
}

PAYLOADS = [
    "/?x=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?q=../../../../etc/passwd",
]


def _match(resp):
    hits = set()
    blob = " ".join(str(v).lower() for v in resp.headers.values())
    blob += " " + resp.text.lower()[:20000]
    for name, sigs in SIGNATURES.items():
        if any(s in blob for s in sigs):
            hits.add(name)
    return hits


def run(target, ctx):
    base = base_url(target)
    findings = []
    vendors = set()
    baseline = ctx.http.get(base, allow_redirects=True)
    if not baseline:
        return make_result(NAME, "no HTTP response", [], {})
    base_status = baseline.status
    vendors |= _match(baseline)
    blocked = 0
    for pl in PAYLOADS:
        r = ctx.http.get(base + pl, allow_redirects=True)
        if not r:
            continue
        vendors |= _match(r)
        if r.status in (403, 406, 429, 501) and r.status != base_status:
            blocked += 1
            findings.append(
                {"signal": "blocked-status", "payload": pl, "detail": str(r.status)}
            )
            warn("payload blocked (" + str(r.status) + "): " + pl)
    for v in sorted(vendors):
        findings.append({"signal": "vendor", "payload": "-", "detail": v})
        good("WAF signature: " + v)
    if not findings:
        good("no WAF/filtering detected")
        summary = "no WAF/filtering detected"
    else:
        summary = (
            ", ".join(sorted(vendors)) if vendors else "filtering behavior"
        ) + " detected"
    return make_result(
        NAME,
        summary,
        findings,
        {"blocked_payloads": blocked, "vendors": sorted(vendors)},
    )
